theme: jekyll-theme-midnight
title: geoschemas.org
description: schema.org extensions for the geosciences
nav:
  - title: Home
    url: /
  - title: Extensions
    url: /extensions
  - title: About
    url: /about
