title: geoschemas.org
description: schema.org extensions for the geosciences
google_analytics: UA-141075626-1
nav:
  - title: Home
    section: Home
    url: /
  - title: Extensions
    section: Extensions
    url: /extensions
  - title: About
    section: About
    url: /about
   - title: Signup
    section: Signup
    url: /signup
    
# See: https://jekyllrb.com/docs/continuous-integration/travis-ci/
exclude: [vendor]
